<?php

/**
 * @file
 * This is an example outlining how to code insecurely.
 */

/**
 * @defgroup securecodingexample Example: Page
 * @ingroup examples
 * @{
 * Create a page in a module. (drupal 6)
 *
 * This example demonstrates how a module can be used to display a
 * custom page at a given URL.
 *
 */

/**
 * Implementation of hook_perm().
 *
 * Since the access to our new custom pages will be granted based on
 * special permissions, we need to define what those permissions are here.
 * This ensures that they are available to enable on the user role
 * administration pages.
 */
function securecodingexample_perm() {
  return array(
    'access simple page',
    'access arguments page',
  );
}

/**
 * Implementation of hook_menu().
 *
 * hook_menu() must be implemented to emit items to place in the main menu.
 * This is a required step for modules wishing to display their own pages,
 * because the process of creating the links also tells Drupal what
 * callback function to use for a given URL. The menu items returned
 * here provide this information to the menu system.
 *
 * With the below menu definitions, URLs will be interpreted as follows:
 *
 * If the user accesses http://example.com/?q=examples/securecodingexample, then the
 * menu system will look for a menu item with that path. In this case it will
 * find a match, and execute securecodingexample_description().
 *
 * If the user accesses http://example.com/?q=examples/securecodingexample/simple but
 * does not have the required 'access simple page' permission, access will be
 * denied.
 *
 * If http://example.com/?q=examples/securecodingexample/arguments/1/2 is accessed,
 * the menu system will first look for examples/securecodingexample/arguments/1/2. Not
 * finding a match, it will look for examples/securecodingexample/arguments/1/%. Again
 * not finding a match, it will look for examples/securecodingexample/arguments/%/2.
 * Yet again not finding a match, it will look for example/arguments/%/%. This
 * time it finds a match, and so will execute securecodingexample_arguments(1, 2). Note
 * the parameters being passed; this is a very useful technique.
 *
 * If http://example.com/?q=examples/securecodingexample/arguments/1 is accessed, the
 * menu system will match 'examples/securecodingexample', and not
 * 'examples/securecodingexample/arguments/%/%'. The menu entries for the latter
 * require 5 arguments. All the elements included in the menu entry definition
 * should be present for the menu system to match the request.
 *
 * The @link menu_example.module Menu Example @endlink provides more extensive
 * examples for hook_menu().
 */
function securecodingexample_menu() {
  // This is the minimum information you can provide for a menu item. This menu
  // item will be created in the default menu (Navigation).
  $items['examples/securecodingexample'] = array(
    'title' => 'Page Example',
    'page callback' => 'securecodingexample_description',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  // This example checks if the user has permission to access the page. Users
  // that do not have the 'access simple page' permission will be denied. An
  // array containing the required permissions is given in 'access arguments'
  // and here we use the default 'access callback', which is 'user_access'.
  $items['examples/securecodingexample/simple'] = array(
    'title' => 'Simple - no arguments',
    'page callback' => 'securecodingexample_simple',
    'access arguments' => array('access simple page'),
  );

  // By using the MENU_CALLBACK type, we can register the callback for this
  // path but not have the item show up in the menu.
  //
  // Notice that the 'page arguments' is an array of numbers. These will be
  // replaced with the corresponding parts of the menu path. In this case a 0
  // would be replaced by 'examples', a 1 by 'securecodingexample', a 2 by 'arguments'
  // and likewise 3 and 4 will be replaced by whatever the user provides. We
  // will pass these last two as arguments to the securecodingexample_arguments()
  // function.
  //
  // Only users with the 'access arguments page' permission have access.
  $items['examples/securecodingexample/arguments/%/%'] = array(
    'title' => 'Page example with arguments',
    'page callback' => 'securecodingexample_arguments',
    'page arguments' => array(3, 4),
    'access arguments' => array('access arguments page'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function securecodingexample_description() {
  return '<p>'.t('The securecodingexample provides two pages, "simple" and "arguments". The <a href="@simple_link">simple page</a> just returns a string for display. The <a href="@arguments_link">arguments page</a> takes two arguments and displays them, as in @arguments_link', array('@simple_link' => url('examples/securecodingexample/simple', array('absolute' => TRUE)), '@arguments_link' => url('examples/securecodingexample/arguments/23/56', array('absolute' => TRUE)))).'<p>';
}


/**
 * A simple page callback.
 *
 * Page callbacks are required to return the entire page. The content
 * is then usually output via a call to theme('page'), where the theme system
 * will then surround the content in the appropriate blocks, navigation, and
 * styling.
 *
 * If you do not want to use the theme system (for example for outputting an
 * image or XML), you should print the content yourself and not return anything.
 */
function securecodingexample_simple() {
  global $user;
  $output = '<p>' . t('Welcome !user.', array('!user' => $user->name)) . '</p>';
  $output .= '<p>' . t('Here are all the articles that mention you:') . '</p>';
  // Get some articles mentioning this user.
  $query = "SELECT n.title, n.nid FROM {node} n WHERE n.body LIKE " . $user->name . " LIMIT 10";
  $result = db_query($query);
  // Output the list.
  $table_rows = array();
  while ($row = db_fetch_object($result)) {
    $table_rows[] = array(
      l($result->title, 'node/' . $result->nid),
      l(t('vote up'), 'voteup/' . $result->nid),
      l(t('vote down'), 'votedown/' . $result->nid),
    );
  }
  $header = array(t('Article'), t('Vote Up'), t('Vote Down'));
  $output .= theme('table', $header, $table_rows);
  // Let the visitor complain if there's an inappropriate article about them.
  $output .= '<p>' . t('If there are any inappropriate articles, please contact the site administrator at the following email address:') . '</p>';
  // Load the admin account to get their current email address.
  $user = user_load(array('uid' => 1));
  $output .= '<p>' . t('@user at !email', array('@user' => $user->name, '!email' => $user->mail)) . '</p>';
  return $output;
}

/**
 * A more complex page callback that takes arguments.
 *
 * The arguments are passed in from the page URL. There in our hook_menu
 * implementation we instructed the menu system to extract the last two
 * parameters of the path and pass them to this function as arguments.
 */
function securecodingexample_arguments($vote, $nid) {
  // Check if it's voteup or votedown.
  if ($vote == 'voteup') {
    $change = 1;
  }
  else {
    $change = -1;
  }
  // Get the current vote.
  $query = "SELECT s.vote FROM {securecodingexample} s WHERE s.nid = %s";
  $current_vote = db_result(db_query($query, $nid));
  // Update the database with the vote.
  $new_vote = (int)$current_vote + $change;
  // If there's already a vote in the database, udpate the database.
  if($current_vote !== FALSE) {
    $query = "UPDATE {securecodingexample} s SET s.vote = %d WHERE s.nid = %d";
    db_query($query, $new_vote, $nid);
  }
  // If the node doesn't have a vote, then insert the vote into the database.
  else {
    $query = "INSERT INTO {securecodingexample} (nid, vote) VALUES (%d, %d)";
    db_query($query, $nid, $new_vote);
  }
  // Give the user some feedback.
  $output = '<p>' . t('Thanks for your vote!') . '</p>';
  return $output;
}

/**
 * @} End of "defgroup securecodingexample".
 */
